# logstash/config/logstash.yml

# This is a configuration file for Logstash, a server-side data processing pipeline that ingests data from multiple sources, transforms it, and then sends it to a "stash" like Elasticsearch.

# The HTTP host that Logstash will bind to.

# To restrict access to your local machine, you can bind it to localhost.
# Uncomment the following line to use this option:
http.host: "127.0.0.1"

# To restrict access to your local network, you can bind it to your machine's local network IP address.
# Replace "your.network.ip.address" with your actual network IP address and uncomment the following line to use this option:
# http.host: "your.network.ip.address"

# To allow access from any network (not recommended due to potential security risks), you can bind it to all network interfaces.
# Uncomment the following line to use this option:
# http.host: "0.0.0.0"

# The Elasticsearch hosts that Logstash will send monitoring data to.
# This is an array of one or more Elasticsearch instances to which Logstash will send its monitoring data.
# In this case, it's sending data to an Elasticsearch instance running on the same Docker network (named "elasticsearch") at port 9200.
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]